# Generated by Django 2.2.4 on 2019-09-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20190930_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headnews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('news', models.CharField(max_length=1000)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
